/* DO NOT EDIT THIS FILE - it is machine generated */
#include "C:\Program Files\Java\jdk-14.0.2\include\jni.h"
#include "C:\Program Files\Java\jdk-14.0.2\include\win32\jni_md.h"
/* Header for class jni */

#ifndef _Included_jni
#define _Included_jni
#ifdef __cplusplus


extern "C" 
{
#endif
/*
 * Class:     jni
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnidemojava_JniDemoJava_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
